version: '3'
services:
  SUGameS:
    image: node:latest
    volumes:
      - ./backend:/usr/src/app/backend
      - ./frontend:/usr/src/app/frontend
    working_dir: /usr/src/app/backend
    command: npm start
    ports: 
    - 80:80
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: sugames
      MONGO_INITDB_ROOT_PASSWORD: rC6k8zOV4u53